### PR TITLE
Fixed auto scratch 

### PR DESCRIPTION
**Pull request by requests1337**
fixed scratch according to recent scratch changes

### CODE REVIEW

**Comment by requests1337** [comment]
imma make it click on all 5 tilrs

**Comment by requests1337** [comment]
let me know if it has any bugs I'll fix em when i have time (except the cooldown bug)

**Comment by requests1337** [comment]
Adding support for more games

**Comment by Maxisboller** [comment]
So is scratch patched unless you are level 100

**Pull request closed without merging**
